@csrf
<div class="grid gap-4 sm:grid-cols-2">
    <div><label for="kode_obat" class="mb-1 block text-sm font-medium">Kode Obat</label><input id="kode_obat" name="kode_obat" value="{{ old('kode_obat', $obat->kode_obat ?? '') }}" required maxlength="20" class="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm">@error('kode_obat')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="nama_obat" class="mb-1 block text-sm font-medium">Nama Obat</label><input id="nama_obat" name="nama_obat" value="{{ old('nama_obat', $obat->nama_obat ?? '') }}" required class="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm">@error('nama_obat')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="kategori_id" class="mb-1 block text-sm font-medium">Kategori</label><select id="kategori_id" name="kategori_id" class="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm">
            <option value="">Pilih kategori</option>@foreach ($kategori as $item)<option value="{{ $item->id_kategori }}" @selected(old('kategori_id', $obat->kategori_id ?? '') == $item->id_kategori)>{{ $item->nama_kategori }}</option>@endforeach
        </select>@error('kategori_id')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="satuan" class="mb-1 block text-sm font-medium">Satuan</label><input id="satuan" name="satuan" value="{{ old('satuan', $obat->satuan ?? '') }}" required maxlength="20" placeholder="Tablet, Strip, Botol" class="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm">@error('satuan')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="harga_beli" class="mb-1 block text-sm font-medium">Harga Beli</label><input id="harga_beli" type="number" name="harga_beli" value="{{ old('harga_beli', $obat->harga_beli ?? 0) }}" required min="0" step="0.01" class="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm">@error('harga_beli')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="harga_jual" class="mb-1 block text-sm font-medium">Harga Jual</label><input id="harga_jual" type="number" name="harga_jual" value="{{ old('harga_jual', $obat->harga_jual ?? 0) }}" required min="0" step="0.01" class="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm">@error('harga_jual')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="stok" class="mb-1 block text-sm font-medium">Stok</label><input id="stok" type="number" name="stok" value="{{ old('stok', $obat->stok ?? 0) }}" required min="0" class="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm">@error('stok')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="stok_minimum" class="mb-1 block text-sm font-medium">Stok Minimum</label><input id="stok_minimum" type="number" name="stok_minimum" value="{{ old('stok_minimum', $obat->stok_minimum ?? 0) }}" required min="0" class="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm">@error('stok_minimum')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="tanggal_kadaluarsa" class="mb-1 block text-sm font-medium">Tanggal Kadaluarsa</label><input id="tanggal_kadaluarsa" type="date" name="tanggal_kadaluarsa" value="{{ old('tanggal_kadaluarsa', isset($obat) && $obat->tanggal_kadaluarsa ? $obat->tanggal_kadaluarsa->format('Y-m-d') : '') }}" class="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm">@error('tanggal_kadaluarsa')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div class="sm:col-span-2"><label for="keterangan" class="mb-1 block text-sm font-medium">Keterangan</label><textarea id="keterangan" name="keterangan" rows="3" class="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm">{{ old('keterangan', $obat->keterangan ?? '') }}</textarea></div>
</div>
<div class="mt-6 flex justify-end gap-3"><a href="{{ route('obat.index') }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50">Batal</a><button type="submit" class="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-medium text-white hover:bg-emerald-700">{{ $submitLabel }}</button></div>